# Generated by Django 5.1 on 2026-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g. President, Treasurer', max_length=100)),
                ('major', models.CharField(blank=True, help_text='e.g. Computer Science, Senior', max_length=200)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('legacy_static_image', models.CharField(blank=True, default='', editable=False, max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
